package br.com.catalogo.mediacollectioncatalog.midia.musical.enums;

public enum GeneroMusical {

    ALTERNATIVE_ROCK,
    AMBIENT,
    BARROCO,
    BLACK_METAL,
    BLUES,
    CLASSICO,
    DEATH_METAL,
    DISCO,
    DOOM_METAL,
    ELETRONICA,
    FUNK,
    GOTHIC,
    GOTHIC_METAL,
    GROOVE_METAL,
    GRUNGE,
    HARD_ROCK,
    HEAVY_METAL,
    HIP_HOP,
    HOUSE,
    INDIE,
    JAZZ,
    METAL,
    MUSICA_BRASILEIRA,
    OPERA,
    POP,
    POP_ROCK,
    POWER_METAL,
    PROGRESSIVE_METAL,
    PROGRESSIVE_ROCK,
    PUNK,
    RAP,
    REGGAE,
    RNB,
    ROCK,
    ROMANTICO,
    SKA,
    SOUL,
    SYMPHONIC_METAL,
    SYNTH_POP,
    TECHNO,
    THRASH_METAL,
    TRANCE;
}
