spring.application.name=user-service

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service_db
spring.datasource.username=SEU_LOGIN
spring.datasource.password=SUA_SENHA
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logs SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=DEBUG

# ==========================
# Configuração do Eureka Client
# ==========================

# Registra este microsserviço no Eureka Server
eureka.client.register-with-eureka=true

# Permite consultar o registro de outros microsserviços
eureka.client.fetch-registry=true

# Endereço do Eureka Server responsável pelo registro e descoberta dos serviços
eureka.client.service-url.defaultZone=http://localhost:8081/eureka

# Utiliza uma porta aleatória para permitir múltiplas instâncias do serviço
server.port=0

# Gera um identificador único para cada instância registrada no Eureka
eureka.instance.instance-id=${spring.application.name}:${random.int[1,50]}

# ==========================
# Configuração do JWT
# ==========================

# Chave utilizada para assinar os tokens JWT
jwt.secret=uma-chave-secreta-bem-grande-e-aleatoria-para-o-projeto